apiVersion: apps/v1
kind: Deployment
metadata:
  name: whisper-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whisper
  template:
    metadata:
      labels:
        app: whisper
    spec:
      containers:
      - name: whisper-api
        image: whisper-backend:v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8001
        resources:
          requests:
            cpu: "1000m"
            memory: "2Gi"
          limits:
            cpu: "2000m"
            memory: "4Gi"
        env:
        - name: MODEL_SIZE
          value: "small"
        - name: DEVICE
          value: "cpu"